// Auto-generated by: npx supabase gen types typescript --project-id <project-ref>
// Replace this file after Phase 2 (database setup)
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
